server:
  port: 8444
  ssl:
    key-store: keystore.p12
    key-store-password: mybackend
    key-store-type: pkcs12
    key-alias: mybackend
    key-password: mybackend

#server:
#  port: 8989

spring:
  ai:
    openai:
      api-key: ${BLOG_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    url: ${BLOG_DB_URL}
    username: ${BLOG_DB_USER}
    password: ${BLOG_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hibernate:
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: ${BLOG_JWT_SECRET}
  tokenExpirationTime: 18000

project:
  folderPath: "files/"